fix build with gcc14
Error:
/usr/src/linux-headers-6.12.25-common/include/linux/stddef.h:8:14: error: passing argument 8 of ‘ieee80211_amsdu_to_8023s’ makes integer from pointer without a cast [-Wint-conversion]
    8 | #define NULL ((void *)0)
      |              ^~~~~~~~~~~
      |              |
      |              void *
/var/lib/dkms/aic8800-pcie/3.0+git20240327.3561b08f-5/build/PCIE/driver_fw/driver/aic8800/aic8800_fdrv/rwnx_rx.c:459:106: note: in expansion of macro ‘NULL’
  459 |                                                                  RWNX_VIF_TYPE(rwnx_vif), 0, NULL, NULL, NULL);
      |                                                                                                          ^~~~

We have to use 0 instead of NULL.